parameters:
- name: stages
  type: stageList
- name: stringWithoutValues
  type: string

extends:
  template: extends-template.yml
  parameters:
    name: ${{ parameters.stringWithoutValues }}
    stages: 
    - stage: intermediate
      jobs:
      - job:
        steps:
        - script: echo ${{ parameters.stringWithoutValues }}
    - template: include-template.yml
      parameters:
        name: ${{ parameters.stringWithoutValues }}
