parameters:
- name: name
  type: string
- name: stages
  type: stageList

stages:
- stage: extends
  jobs:
  - job:
    steps: 
    - script: echo ${{ parameters.name }}
      displayName: parameters.name
    - script: echo $(varFromStringWithhoutValues)
      displayName: varFromStringWithhoutValues
    - script: echo $(varWithFormatTemplate)
      displayName: varWithFormatTemplate
    - script: echo $(varWithFormatRuntime)
      displayName: varWithFormatRuntime    
    - script: echo $(Build.BuildNumber)
      displayName: Build.BuildNumber   
    - script: echo $(Build.SourceVersionMessage)
      displayName: Build.SourceVersionMessage  
    - script: echo $(System.StageDisplayName)
      displayName: System.StageDisplayName  
    - script: echo $(System.StageName)
      displayName: System.StageName
- ${{ each stage in parameters.stages }}:
  - ${{ stage }}
